/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NoteRouteImport } from './routes/$note'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ENoteRouteImport } from './routes/e.$note'

const NoteRoute = NoteRouteImport.update({
  id: '/$note',
  path: '/$note',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ENoteRoute = ENoteRouteImport.update({
  id: '/e/$note',
  path: '/e/$note',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$note': typeof NoteRoute
  '/e/$note': typeof ENoteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$note': typeof NoteRoute
  '/e/$note': typeof ENoteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$note': typeof NoteRoute
  '/e/$note': typeof ENoteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$note' | '/e/$note'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$note' | '/e/$note'
  id: '__root__' | '/' | '/$note' | '/e/$note'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NoteRoute: typeof NoteRoute
  ENoteRoute: typeof ENoteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$note': {
      id: '/$note'
      path: '/$note'
      fullPath: '/$note'
      preLoaderRoute: typeof NoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$note': {
      id: '/e/$note'
      path: '/e/$note'
      fullPath: '/e/$note'
      preLoaderRoute: typeof ENoteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NoteRoute: NoteRoute,
  ENoteRoute: ENoteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
